In [1]:
a = 1

In [2]:
a

1

In [3]:
import numpy as np

In [4]:
print(np.array([3]))

[3]


In [1]:
import torch

# list

In [2]:
a = torch.tensor([1, 2, 3])

In [3]:
a

tensor([1, 2, 3])

In [4]:
a + 5

tensor([6, 7, 8])

In [5]:
a

tensor([1, 2, 3])